import type { Metadata } from 'next'
import Articles from '@/app/components/Articles'
import Features from '@/app/components/Features'
import Footer from '@/app/components/Footer'
import HeroContent from '@/app/components/HeroContent'
import NavBar from '@/app/components/NavBar'

export const metadata: Metadata = {
  title: 'Simple Next.js',
  description: 'Generated by Simple Next.js',
}

const PageHome = () => (
  <main className="flex min-h-screen flex-col justify-center md:max-w-7xl">
    <NavBar />
    <HeroContent />
    <Features />
    <Articles />
    <Footer />
  </main>
)

export default PageHome
